// <auto-generated />
using BiliAnalytics.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BiliAnalytics.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514102117_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("BiliAnalytics.Core.Models.HistoryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bvid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CoinCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DanmakuCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FavoriteCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LikeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecordedAt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShareCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoBvid")
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("VideoBvid");

                    b.HasIndex("Bvid", "RecordedAt");

                    b.ToTable("history");
                });

            modelBuilder.Entity("BiliAnalytics.Core.Models.Video", b =>
                {
                    b.Property<string>("Bvid")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("AddedDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMonitoring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Bvid");

                    b.HasIndex("IsMonitoring");

                    b.ToTable("videos");
                });

            modelBuilder.Entity("BiliAnalytics.Core.Models.HistoryRecord", b =>
                {
                    b.HasOne("BiliAnalytics.Core.Models.Video", null)
                        .WithMany("History")
                        .HasForeignKey("VideoBvid");
                });

            modelBuilder.Entity("BiliAnalytics.Core.Models.Video", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
